#!/bin/bash

isodir="/kvm/nfs/_iso"
imgdir_local="/kvm/img"
imgdir_remote="/kvm/nfs/"
tmpdir="$(mktemp -d)"
mountpoint="$(mktemp -d)"
loopdev="/dev/loop$RANDOM"

if [ "$1" == "-h" ]; then
	echo 'Usage: mountkvm <imagename>'
	echo '       mountkvm -u(mount)'
	echo '       mountkvm -l(ist)'
	exit 0
fi

#file
dimg="$1"

#list function
function list_templates {
	ipath="$1"
	echo "Images available for mount in $ipath:"
	ls -1 "$ipath" | egrep '\.(img|gz)$'
}

function cleanup_and_exit {
	umount -f "$mountpoint"
	kpartx -d "$loopdev"
	losetup -d "$loopdev"
	rmdir -f "$tmpdir" "$mountpoint" "$loopdev"
	exit "$1"
}

#mount function
function mount_image {
	simg="$1"
	#if everything is ok check if image is gzip template
	if echo "$simg" | egrep '\.gz$'; then
		#image is gzip, unpack it and schedule repack later
		rm -f /var/run/kvmmount_repack
		echo 'gzrepack=1' >/var/run/kvmmount_repack
		echo "gzorgname=$simg" >>/var/run/kvmmount_repack
		echo "tmpfile=$tmpdir/$dimg.tmp" >>/var/run/kvmmount_repack
		gunzip -dc "$simg" > "$tmpdir/$dimg.tmp"
		simg="$tmpdir/$dimg.tmp"
	fi
	#now we have a raw img file - mount it on loop
	losetup "$loopdev" "$simg"
	#kpartx
	kpartx -sa "$loopdev"
	#trial and error which partition is the right one, try 1
	for partition in "/dev/mapper/${loop}p"*; do
		mount "$partition" "$mountpoint" && break
	done
	if ! mountpoint "$mountpoint"; then
		echo "Error: could not find mountable partition - exiting"
		cleanup_and_exit 1
	fi
}

if [ "$1" == "-l" ]; then
	list_templates "$isodir"
	echo
	list_templates "$imgdir_local"
	echo
	list_templates "$imgdir_remote"
	exit 0
fi

if [ "$1" == "-u" ]; then
	if ! mountpoint -q "$mountpoint"; then
		echo "Error: nothing mounted"
		exit 0
	fi
	echo "Unmounting current mount"
	umount -f "$mountpoint"
	kpartx -d "$loopdev"
	losetup -d "$loopdev"
	echo "Unmount done - checking if re-gzip is required"
	#check if a gzip repack is scheduled
	if [ -f /var/run/kvmmount_repack ]; then
		echo "Gzip repack required - running now"
		gzrepack=0
		gzorgname=0
		tmpfile=0
		source /var/run/kvmmount_repack
		if [ "$gzrepack" == "1" ]; then
			rm -f "$gzorgname"
			gzip -c "$tmpfile" > "$gzorgname"
			echo "Repack done"
			rm /var/run/kvmmount_repack
			rm "$tmpfile"
		fi
	else
		echo "No re-gzip required"
	fi
	exit 0
fi

#mount
#check where file is and run mount subprocess
if [ -f "$isodir/$dimg" ]; then
	mount_image "$isodir/$dimg"
elif [ -f "$imgdir_local/$dimg" ]; then
	mount_image "$imgdir_local/$dimg"
elif [ -f "$imgdir_remote/$dimg" ]; then
	mount_image "$imgdir_remote/$dimg"
else
	echo "Error: Image file not found or wrong command - exiting"
fi

cleanup_and_exit 0